# Generated by Django 2.2.28 on 2022-07-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220727_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
